### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by Xu-Jianjun** [MCLAB-OCR/KnowledgeMiningWithSceneText#2]
请问代码还有开源计划吗？

**Comment by ShinyJJwei** [comment]
同问

**Comment by lanfeng4659** [comment]
会的，之前因该算法是国基金重点项目内的一个重要demo，所以需要在demo展示后给code。近期demo答辩完，就给训练的模型和code。在这之前，可以随时联系我，讨论关于论文细节问题。




发件人："budhdksala" ***@***.***>
发送日期：2022-10-27 15:26:23
收件人："lanfeng4659/KnowledgeMiningWithSceneText" ***@***.***>
抄送人：
主 题：Re: [lanfeng4659/KnowledgeMiningWithSceneText] 代码 (Issue #2)


同问

**Comment by Xu-Jianjun** [comment]
你好，贵组的项目结题了吗？代码有开源时间表吗？还有，Bottles这个数据集好像很嘈杂，能开源相关的模型和代码吗？

**Comment by Leojc** [comment]
您好，预计年后会开源，目前在实习，代码在公司无法进行外传
