### ISSUE TITLE
复现精度问题

### ISSUE THREAD

**Issue by Xu-Jianjun** [MCLAB-OCR/KnowledgeMiningWithSceneText#3]
按照您的配置文件，在bottles数据集精度上存在比较大的差距，可以提供更详细的配置文件吗？

**Comment by Leojc** [comment]
可以提供log文件看看吗？

**Comment by Leojc** [comment]
看了一下你的log，你修改了BATCH_SIZE_PERGPU、ACCUM_ITERS、NUM_EPOCHS，可以还原试试看。若要调整batchsize的话，保持BATCH_SIZE_PERGPU * ACCUM_ITERS = 256。
